name: Update Judges Map Data

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install jupyter nbconvert
          pip install -r requirements.txt
          
      - name: Run notebook
        run: |
          jupyter nbconvert --to notebook --execute map_updater.ipynb --output executed_notebook.ipynb --debug

