name: Update Judges Map Data

on:
  push:
    paths:
      - '**.ipynb'

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry dependencies
        run: |
          pip install poetry
          poetry install
          poetry add jupyter nbconvert


      - name: Run notebook
        run: |
          jupyter nbconvert --to notebook --execute my_notebook.ipynb --output executed_notebook.ipynb
