name: Update Judges Map Data

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI

permissions:
  contents: write  # 🔑 This gives the token permission to push

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install jupyter nbconvert
          pip install -r requirements.txt
          
      - name: Run notebook
        run: |
          jupyter nbconvert --to notebook --execute map_updater.ipynb --output executed_notebook.ipynb --debug

      - name: Commit changes
        run: |
          git config --local user.email "mthatcherclark@users.noreply.github.com"
          git config --local user.name "Update Judges Map Data Action"
          git add docs/courts.geojson docs/judges.json # Add both files
          git commit -m "Update geojson files from notebook" || echo "No changes to commit"
          git push
